---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1525344/annahl
    - export PUBLICPATH=/home/u1525344/public_html/annahl
    # Copy Core Files
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp spark $DEPLOYPATH
    # Copy Public Assets (Folders Only) - EXCLUDING index.php
    - /bin/cp -R public/js $PUBLICPATH
    - /bin/cp -R public/template $PUBLICPATH

