<?php
/**
 * Generate Mushaf Pages from Quran.com API
 * This script fetches data directly from Quran.com API for Juz 30
 * to ensure 100% accuracy
 */

echo "Fetching Juz 27-30 data from Quran.com API...\n";

$mushafPages = [];

// Fetch all pages from 522 to 604 (Juz 27-30)
for ($page = 522; $page <= 604; $page++) {
    echo "Fetching page $page...\n";
    
    $url = "https://api.quran.com/api/v4/verses/by_page/$page";
    $json = file_get_contents($url);
    
    if ($json === false) {
        die("Error fetching page $page\n");
    }
    
    $data = json_decode($json, true);
    $verses = $data['verses'];
    
    if (empty($verses)) {
        echo "Warning: No verses found for page $page\n";
        continue;
    }
    
    // Group verses by surah
    $pageData = [];
    $currentSurah = null;
    $startVerse = null;
    $endVerse = null;
    $juzNumber = $verses[0]['juz_number']; // Capture Juz number from first verse
    
    foreach ($verses as $verse) {
        $surahNum = (int)explode(':', $verse['verse_key'])[0];
        $verseNum = (int)$verse['verse_number'];
        
        if ($currentSurah === null) {
            // First verse on this page
            $currentSurah = $surahNum;
            $startVerse = $verseNum;
            $endVerse = $verseNum;
        } elseif ($currentSurah === $surahNum) {
            // Same surah, extend range
            $endVerse = $verseNum;
        } else {
            // New surah, save previous and start new
            $pageData[] = [
                'surah' => $currentSurah,
                'from' => $startVerse,
                'to' => $endVerse
            ];
            
            $currentSurah = $surahNum;
            $startVerse = $verseNum;
            $endVerse = $verseNum;
        }
    }
    
    // Save last surah
    if ($currentSurah !== null) {
        $pageData[] = [
            'surah' => $currentSurah,
            'from' => $startVerse,
            'to' => $endVerse
        ];
    }
    
    $mushafPages[$page] = [
        'juz' => $juzNumber,
        'verses' => $pageData
    ];
    
    // Be nice to the API
    usleep(100000); // 100ms delay
}

// Save to JSON file with metadata
$output = array_merge(
    ["__info" => "Generated by fetch_quran_api.php - Pulls data from Quran.com API v4"],
    $mushafPages
);
$jsonOutput = json_encode($output, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE);
$outputFile = __DIR__ . '/mushaf_pages_complete.json';

if (file_put_contents($outputFile, $jsonOutput)) {
    echo "\n✓ Generated mushaf_pages_complete.json\n";
    echo "✓ Total pages: " . count($mushafPages) . "\n";
    echo "✓ File saved to: $outputFile\n";
    echo "\nData source: Quran.com API (100% accurate)\n";
} else {
    die("Error writing to file\n");
}
